import Head from 'next/head'

import {Canvas} from "@react-three/fiber";

export default function Home() {
  return (
    <div className='h-screen w-full flex bg-slate-50 items-center justify-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='  lg:w-9/12 lg:h-5/6 '>
        <MainScene></MainScene>        
      </div>
    </div>
  )
}
function MainScene(){
  return(
    <Canvas>
      <pointLight position={[10,10,10]}></pointLight>
      <mesh>
        <planeBufferGeometry args={[3,5]}>  </planeBufferGeometry>
        <meshStandardMaterial color={"lightBlue"}></meshStandardMaterial>
      </mesh>
    </Canvas>
  );
}